### ISSUE TITLE
Lack of essential information in the README

### ISSUE THREAD

**Issue by panicz** [NKb03/Hextant#1]
How do I build and run the project?

**Comment by schleifenkauz** [comment]
First thank you for your interest. The project is in a very early stage so there you can not really use it.
Maybe I should make that more clear in the README. But I have a little example showing the concept of the editor. It's a small calculator. Tomorrow I will provide information in the readme on how to build it.

**Comment by panicz** [comment]
I don't expect to use it, but I am really curious how it looks :)
Perhaps even a screen shot or a short video would be helpful.

I recently started a project whose description could sound similar [it's connected with the rectangle challenge that I have been describing on my Quora blog], and so I've been wondering of there are any ideas that I could steal from you ;] (or colaborate, maybe)

**Comment by schleifenkauz** [comment]
Hi Panicz,
I finally managed to record a little screencast and create a jar file that you can run to try the calculator yourself. [Here](https://github.com/NKb03/Hextant/wiki/The-calculator-example)  is the wiki page that describes how to run the calculator.
I would be really happy to colaborate with you.

**Comment by panicz** [comment]
:) Thanks for the demo!
I'm not sure if I'm doing everything properly, but when I run
`$ java -jar hextant_calculator.jar`
I get
`Error: Could not find or load main class org.nikok.hextant.core.expr.ExprEditorViewTest`
(the video is sufficient for conveying the idea, though, so I'm closing the ticket)

Hextant seems different than what I have in mind (I'll write more in a Quora DM), but it resembles the way Lisp programmers use Emacs (with SLIME for Common Lisp, Geiser for Scheme and CIDER for Clojure) - I wonder if you've ever used any of those?

**Comment by schleifenkauz** [comment]
By mistake closed this issue:)

**Comment by schleifenkauz** [comment]
Ah now I see that you were that :) going to close it

**Comment by schleifenkauz** [comment]
I wonder if we should communicate via another tool, any ideas?

**Comment by schleifenkauz** [comment]
Going to try the my jar file another time, maybe my mistake

**Comment by panicz** [comment]
I guess we could use desktop sharing via Hangouts

**Comment by schleifenkauz** [comment]
Good idea, I didn't use it before but it looks nice.
And no I never used scheme. 
I tried the jar file and on my machine it functions. I just have to double-click on it after downloading it with chrome.  I use windows

**Comment by schleifenkauz** [comment]
I had to eat with my parents. My computer time is over, let us talk tomorrow, let me know when you have time, I will call you

**Comment by panicz** [comment]
I probably will be away from computer tomorrow (I try not to use it on sundays, and my girlfriend is comming home after two weeks being away). But I'm updating my blog entries concerning the Recangle Challenge, uploading the videos of the running application, so that you can watch it (it's not as silly as it may seem ;])
